#ifndef POLYCYPT_ERROR_H
#define POLYCYPT_ERROR_H

enum {
	POLYCYPT_ERROR_SUCCESS,
	POLYCYPT_ERROR_GENALG,
  POLYCYPT_ERROR_COMPILE,
  POLYCYPT_ERROR_LINK,
  POLYCYPT_ERROR_MAKEPCF,
  POLYCYPT_ERROR_READ_FILE,
  POLYCYPT_ERROR_WRITE_FILE,
	POLYCYPT_ERROR_UNKNOW,
	POLYCYPT_ERROR_NUMBER
};

#endif
